### ISSUE TITLE
Event Close Youtube when youtube is running

### ISSUE THREAD

**Issue by tuananh1998hust** [ihadeed/CordovaYoutubeVideoPlayer#6]
When youtube is running and i close youtube, callback function close youtube can not call

**Comment by JoelAH** [comment]
Hi, Im getting the same issue as well. Is there any fix? See my stacktrace below:

AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=242, result=0, data=null} to activity {[omit].MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
04-18 14:33:23.492  6365  6365 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:4342)
04-18 14:33:23.492  6365  6365 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3625)
04-18 14:33:23.492  6365  6365 E AndroidRuntime:        ... 10 more
04-18 14:33:23.492  6365  6365 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
04-18 14:33:23.492  6365  6365 E AndroidRuntime:        at com.bunkerpalace.cordova.YoutubeVideoPlayer.onActivityResult(YoutubeVideoPlayer.java:39)
04-18 14:33:23.492  6365  6365 E AndroidRuntime:        at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:159)
04-18 14:33:23.492  6365  6365 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:359)
04-18 14:33:23.492  6365  6365 E AndroidRuntime:        at android.app.Activity.dispatchActivityResult(Activity.java:7235)
04-18 14:33:23.492  6365  6365 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:4338)

**Comment by tuananh1998hust** [comment]
i create custom native code and resolve issues

**Comment by gmoraiz** [comment]
any solution for this problem?

**Comment by JensUweB** [comment]
Can confirm, close event doesn't work for me too. @tuananh1998hust can you share that code, so that everyone else can get this working too, please?
